//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

namespace Machine.Specifications.Mvc.Specs
{
    [Subject(typeof(ModelTypeAnd<>))]
    public class when_the_model_type_and_is_asked_for_the_and_bit
    {
        static ModelTypeAnd<string> modelTypeAnd;
        static string model;
        static string result;

        Establish context = () =>
            {
                model = "The string";
                modelTypeAnd = new ModelTypeAnd<string>(model);
            };

        Because of = () => result = modelTypeAnd.And();

        It should_return_the_model = () => result.ShouldEqual(model);
    }
}   