//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

namespace Machine.Specifications.Mvc.Specs
{
    using System.Web.Mvc;

    [Subject(typeof(RedirectResultAnd))]
    public class when_the_redirect_result_and_is_asked_for_the_and_bit
    {
        static RedirectResultAnd viewResultAnd;
        static RedirectResult redirectResult;
        static RedirectResult result;

        Establish context = () =>
            {
                redirectResult = new RedirectResult("TheUrl");
                viewResultAnd = new RedirectResultAnd(redirectResult);
            };

        Because of = () => result = viewResultAnd.And();

        It should_return_the_redirect_result = () => result.ShouldEqual(redirectResult);
    }
}   