//-------------------------------------------------------------------------------------------------
// <auto-generated> 
// Marked as auto-generated so StyleCop will ignore BDD style tests
// </auto-generated>
//-------------------------------------------------------------------------------------------------

namespace Machine.Specifications.Mvc.Specs
{
    using System.Web.Mvc;

    [Subject(typeof(RedirectToRouteResultAnd))]
    public class when_the_redirect_to_route_result_and_is_asked_for_the_and_bit
    {
        static RedirectToRouteResultAnd redirectToRouteResultAnd;
        static RedirectToRouteResult redirectToRouteResult;
        static RedirectToRouteResult result;

        Establish context = () =>
            {
                redirectToRouteResult = new RedirectToRouteResult("", null);
                redirectToRouteResultAnd = new RedirectToRouteResultAnd(redirectToRouteResult);
            };

        Because of = () => result = redirectToRouteResultAnd.And();

        It should_return_the_redirect_to_route_result = () => result.ShouldEqual(redirectToRouteResult);
    }
}   